apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-beehive
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.200 - 192.168.0.205
  autoAssign: true
  avoidBuggyIPs: false
